### ISSUE TITLE
string "constructor" will produce strange output

### ISSUE THREAD

**Issue by matthiasabele** [emish89/smile2emoji#176]
If you pass the string "constructor" to checkText() , you will get the following string back: "function Object() { [native code] }"

**To Reproduce**
add this basic snippet:

`console.log(checkText("constructor"));`

**Expected behavior**
the function should return "constructor"

**Desktop (please complete the following information):**
 - OS: Windows
 - any
 - Version latest modern browsers

**Comment by emish89** [comment]
should be solved with the 3.6.1 release, thanks a lot
