### ISSUE TITLE
Demo Website

### ISSUE THREAD

**Issue by Nepaltechguy2** [emish89/smile2emoji#2]
**Is your feature request related to a problem? Please describe.**
I wanted to test this out before downloading it, would it be possible for you to create a small demo website? I could create it if needed. 

**Describe the solution you'd like**
A demo website (even one hosted on gh-pages) would be nice :)

I could create and PR, if this is acceptable :)

**Comment by emish89** [comment]
Hi sorry, didn't read it! Yes it will be fantastic if you want to contribute!
Thanks

**Comment by emish89** [comment]
https://codepen.io/emish89/pen/YzGrvVK  @Nepaltechguy2

**Comment by Nepaltechguy2** [comment]
I intend to work on this eventually, just super busy at the moment. I'll get back to you in a month or so, hopefully.
