### ISSUE TITLE
New lines, first characters are not replaced

### ISSUE THREAD

**Issue by scei** [emish89/smile2emoji#253]
**Describe the bug**
I use the module for a textarea.
Pressing enter and try to enter something for replacement won't work. It needs at least one space before.

**To Reproduce**
1. Create a textarea with checkText used in the EventListener
2. Press Enter to get a new line in the text area
3. Enter :-) or any other string to be replaced as the first characters of the line

**Expected behavior**
The entered string at the beginning of the line are replaced with the emoji.

**Screenshots**
![image](https://github.com/emish89/smile2emoji/assets/9378320/247e83e2-e0c3-4883-b806-d490a674c325)

**Desktop (please complete the following information):**
 - OS: Windows, Android
 - Browser Chrome, Edge,...

**Comment by emish89** [comment]
fixed in 3.8.4
