### ISSUE TITLE
index.js needs to be renamed to index.cjs to work...

### ISSUE THREAD

**Issue by DanyPell** [emish89/smile2emoji#320]
Using Next.js 14. Getting this error in console:

```
stderr:  ⨯ ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/admin/Development/ff/ff-web/node_modules/smile2emoji/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/admin/Development/ff/ff-web/node_modules/smile2emoji/lib/index.js:1:36
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:430:15) {
  page: '/app'
}
```

and on web page:
```
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/admin/Development/ff/ff-web/node_modules/smile2emoji/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

Renaming index.js to index.cjs did fix it, along with changing the path in package.json:

  "main": "./lib/index.cjs",
  "module": "./lib/index.cjs",
  
  
  Please fix it so we don't need to update a node module :)

**Comment by sebamarynissen** [comment]
I had this problem as well (not on Next.js, but because my gui tests run on Node) and filed a fix for it in #327.

**Comment by emish89** [comment]
sorry for totally losing this issue! I will check the PR from @sebamarynissen

**Comment by RobsonMi** [comment]
I am still seeing some issues using this module with Quasar/Vite.

With normal `import { checkText } from "smile2emoji";` it fails stating that no checkText is exported. When I instead try `import * as smile2emoji from "smile2emoji";` then it just states `ReferenceError: exports is not defined`.

When I revert to `3.8.6` there are no issues.

**Comment by sebamarynissen** [comment]
Works fine for me on Vite 5.0.12. From the error you have it looks like Vite doesn't properly treat it as a dependency (for which Vite will transpile cjs to esm), but tries to do a direct import of an unknown file extension. I think you might need to upgrade Vite, perhaps that the version you are using does not support `.cjs` extensions.

**Comment by emish89** [comment]
I'm thinking about revert last commit, create last 2.x version and then create a major version with this PR, considering it a breaking change.

**Comment by sebamarynissen** [comment]
@emish89 I think there's a solution with conditional exports as well, if you give me a few minutes I will file a PR.

**Comment by sebamarynissen** [comment]
See https://github.com/emish89/smile2emoji/pull/329.
